{% set name = "mordredcommunity" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mordredcommunity-{{ version }}.tar.gz
  sha256: 6a7b0dc85abdbdcfcbcc0ba91c70555f81391e14ea5cc69dc546d5a8e811be48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - rdkit
    - six
    - numpy
    - networkx

test:
  imports:
    - mordred

about:
  home: https://github.com/JacksonBurns/mordred-community
  summary: Community-Maintained Version of mordred
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
