{% set name = "mordredcommunity" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mordredcommunity-{{ version }}.tar.gz
  sha256: ce2072651e0df22278dd34d11389d9093e841a88f9f081d9c5706159d242718c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - pip
  run:
    - python >=3.8
    - rdkit
    - six
    - numpy
    - networkx
    - packaging
    - pandas

test:
  imports:
    - mordred

about:
  home: https://github.com/JacksonBurns/mordred-community
  summary: Community-Maintained Version of mordred
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JacksonBurns
